<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Content agregator</title>
    <link href="/bootstrap/dist/css/bootstrap.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/bootstrap/dist/js/bootstrap.js"></script>
</head>
<body>
<div class="container">
    <?php echo $this->layout()->content; ?>
</div>

</body>
</html>

