<?php $section = $this->section; ?>

<h2><?php echo $section['title']; ?></h2>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Label</th>
            <th>Occurences</th>
        </tr>
    </thead>
    <?php foreach($section['result'] as $label => $value) { ?>
        <tr>
            <td><?php echo $label; ?></td>
            <td><?php echo $value; ?></td>
        </tr>
    <?php } ?>
</table>